### ISSUE TITLE
Restyle Frontend -  Resources Page

### ISSUE THREAD

**Issue by minhngo3818** [Computer-Science-Club-OCC/Computer-Science-Club-OCC.github.io#98]
The current ui for resources page is not good-looking. In addition, the old styling uses purely CSS classes. In this issue, the resource page need restyling to make it look good and replace the old css in js file with tailwind CSS. Orange base color is `#ff9617`. Hover effect and animation are up to programmers.

This task can have many contributors to work on this issue.
Any fascinating ideas for restyling this page are welcomed. Here is the demo design to rely on. 
<img src="https://user-images.githubusercontent.com/78233689/195009134-5822e4b9-abff-4962-91e0-48797a912200.png" width="600px" height="800px" />

**Comment by SabujGolui** [comment]
Assign it to me ill like to work on it

**Comment by mfonPeeter** [comment]
Hi @SabujGolui. I've been assigned to restyle the frontend of the event page widget of the website. Since you already started working before me on another section of the page with Tailwind CSS. I wanted to know if you are making use of the Tailwind CSS default media queries or if you defined yours. Thanks and I will be waiting for your response.

**Comment by SabujGolui** [comment]
I'm using default media queries

**Comment by mfonPeeter** [comment]
Okay. Thanks for the information

**Comment by minhngo3818** [comment]
This task is postponed. Please wait for final design.

**Comment by minhngo3818** [comment]
This issue will be addressed in new issues for styling tab components in resources pages.
